# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


HEADERS += ./qt_test.h
SOURCES += ./main.cpp \
    ./qt_test.cpp
FORMS += ./qt_test.ui
RESOURCES += qt_test.qrc
